### ISSUE TITLE
请问为什么我在N-Caltech101上训练的mAP与论文中差这么大？

### ISSUE THREAD

**Issue by liyke** [Windere/EAS-SNN#1]
![image](https://github.com/user-attachments/assets/e32ac8fd-3d84-4bb9-be69-5bc005521eb5)

**Comment by Windere** [comment]
**可能的原因有：**
1. N-Caltech 101数据集不提供原始的数据划分，不同的数据划分对性能存在影响 
2. 在N-Caltech 101和Gen1实验中采用的脉冲神经网络backbone代码，默认参数有一些区别，而main分支中的版本主要用于Gen1和1Mpx数据集

**为了更好的复现论文中N-Caltech 101的结果，请考虑：**
1.  切换到ncaltech-rep分支 （git checkout ncaltech-rep）
2.  请使用分享的[数据集划分文件](https://drive.google.com/drive/folders/1Ie47P96aTmdDxWKC16_-KPTWA6zw89Cc)，并按照如下文件结构放置：
![image](https://github.com/user-attachments/assets/2291ab73-c63a-4692-bf9f-5495b6631cff)
3. N-Caltech 101数据集上使用SYOLOX-M结构训练得到的权重文件和tensorboard日志[在这里](https://drive.google.com/drive/folders/1x9hEhnjlGFbu-lQCSgibaNALKyKy0-qU)以供参考， 使用如下命令测试:
` python eval_event.py -n e-yolox-m  -d 1 -b 8 -c ./pretrained/best_ckpt.pth --conf 0.001  data_num_workers 2 embedding arsnn seed 80  data_dir  ${your data path} Tm 4  T 3 spike_attach True  thresh 1 readout sum  write_zero True  use_spike True spike_fn atan window 0 alpha 1.5`
应当能够获得与论文匹配的结果
![image](https://github.com/user-attachments/assets/8f3507c3-a829-4b92-9b64-c7905b472836)
